// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_SIMPLEMAP_MAP_EXPERIMENT_H_
#define FLATBUFFERS_GENERATED_SIMPLEMAP_MAP_EXPERIMENT_H_

#include "flatbuffers/flatbuffers_ramp.h"

namespace Map {
namespace Experiment {

struct MainT;

struct MainT : public flatbuffers::NativeTable {
  rMap<rString, int32_t> testMap1;
  rMap<int32_t, rString> testMap2;
  MainT(RampAlloc *alloc)
      : testMap1(SAllocator<std::pair<const rString, int32_t> >(alloc)),
        testMap2(SAllocator<std::pair<const int32_t, rString> >(alloc)) {
  }
};

}  // namespace Experiment
}  // namespace Map

#endif  // FLATBUFFERS_GENERATED_SIMPLEMAP_MAP_EXPERIMENT_H_
